sudo: required
services:
  - docker 

before_install:
  - docker build -t abhatiaco/docker-react -f Dockerfile.dev .

script:
  - docker run abhatiaco/docker-react npm run test -- --coverage

deploy:
  provider: elaticbeanstalk
  region: "us-west-2"
  app: "docker-react"
  env: "Docker-react-env"
  bucket_name: "elasticbeanstalk-us-west-2-713490454045"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "AWS_SECRET_KEY"


